<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jackpots</name>
   <tag></tag>
   <elementGuidId>c2b2284c-62bd-4889-b70c-d12df8c7ed81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;templatestyles__Desktop-sc-1wrihlj-6 cLplfU&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 templatestyles__Container-sc-1wrihlj-1 dZbjFV&quot;]/div[@class=&quot;Categorystyles__Root-d7h34r-0 bNTpBK&quot;]/div[@class=&quot;Categorystyles__Row-d7h34r-10 fVmxnM&quot;]/div[@class=&quot;Navigationstyles__MenuWrapper-p060u5-0 fejVwI&quot;]/div[@class=&quot;Navigationstyles__Menu-p060u5-1 fRbAGx&quot;]/a[3][count(. | //a[@href = '/en/casino/jackpots/' and (text() = 'Jackpots' or . = 'Jackpots')]) = count(//a[@href = '/en/casino/jackpots/' and (text() = 'Jackpots' or . = 'Jackpots')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div[2]/div/div/div/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/casino/jackpots/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jackpots</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;templatestyles__Desktop-sc-1wrihlj-6 cLplfU&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 templatestyles__Container-sc-1wrihlj-1 dZbjFV&quot;]/div[@class=&quot;Categorystyles__Root-d7h34r-0 bNTpBK&quot;]/div[@class=&quot;Categorystyles__Row-d7h34r-10 fVmxnM&quot;]/div[@class=&quot;Navigationstyles__MenuWrapper-p060u5-0 fejVwI&quot;]/div[@class=&quot;Navigationstyles__Menu-p060u5-1 fRbAGx&quot;]/a[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div[2]/div/div/div/div/a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPACE MISSIONS'])[2]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Games'])[2]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='greentube'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/casino/jackpots/')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/a[3]</value>
   </webElementXpaths>
</WebElementEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jackpots</name>
   <tag></tag>
   <elementGuidId>c2b2284c-62bd-4889-b70c-d12df8c7ed81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;templatestyles__Desktop-sc-1wrihlj-6 cLplfU&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 templatestyles__Container-sc-1wrihlj-1 dZbjFV&quot;]/div[@class=&quot;Categorystyles__Root-d7h34r-0 bNTpBK&quot;]/div[@class=&quot;Categorystyles__Row-d7h34r-10 fVmxnM&quot;]/div[@class=&quot;Navigationstyles__MenuWrapper-p060u5-0 fejVwI&quot;]/div[@class=&quot;Navigationstyles__Menu-p060u5-1 fRbAGx&quot;]/a[3][count(. | //a[@href = '/en/casino/jackpots/' and (text() = 'Jackpots' or . = 'Jackpots')]) = count(//a[@href = '/en/casino/jackpots/' and (text() = 'Jackpots' or . = 'Jackpots')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div[2]/div/div/div/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/casino/jackpots/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jackpots</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;templatestyles__Desktop-sc-1wrihlj-6 cLplfU&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 templatestyles__Container-sc-1wrihlj-1 dZbjFV&quot;]/div[@class=&quot;Categorystyles__Root-d7h34r-0 bNTpBK&quot;]/div[@class=&quot;Categorystyles__Row-d7h34r-10 fVmxnM&quot;]/div[@class=&quot;Navigationstyles__MenuWrapper-p060u5-0 fejVwI&quot;]/div[@class=&quot;Navigationstyles__Menu-p060u5-1 fRbAGx&quot;]/a[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div[2]/div/div/div/div/a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPACE MISSIONS'])[2]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Games'])[2]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='greentube'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/casino/jackpots/')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/a[3]</value>
   </webElementXpaths>
</WebElementEntity>
>>>>>>> branch 'master' of https://github.com/WhiteOrg/SCAutoTests
