<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Review_1</name>
   <tag></tag>
   <elementGuidId>ccf32599-53cc-4573-9af2-36b251fb2c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;DashboardCardstyes__Root-sc-8py5uv-0 ibetEP&quot;]/div[@class=&quot;DashboardCardstyes__Container-sc-8py5uv-2 gsnPml&quot;]/div[@class=&quot;DashboardCardstyes__Wrapper-sc-8py5uv-1 kpPOAp&quot;]/div[@class=&quot;DashboardCardstyes__LinkWrapper-sc-8py5uv-5 gMOGcJ&quot;]/a[@class=&quot;Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE&quot;][count(. | //*[@class = 'Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE' and @href = '/en/account/limits/' and (text() = 'Review' or . = 'Review')]) = count(//*[@class = 'Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE' and @href = '/en/account/limits/' and (text() = 'Review' or . = 'Review')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/account/limits/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Review</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;DashboardCardstyes__Root-sc-8py5uv-0 ibetEP&quot;]/div[@class=&quot;DashboardCardstyes__Container-sc-8py5uv-2 gsnPml&quot;]/div[@class=&quot;DashboardCardstyes__Wrapper-sc-8py5uv-1 kpPOAp&quot;]/div[@class=&quot;DashboardCardstyes__LinkWrapper-sc-8py5uv-5 gMOGcJ&quot;]/a[@class=&quot;Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Review')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Always Play Safe'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep Your Account Secure'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Review']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/account/limits/')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Review')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Review_1</name>
   <tag></tag>
   <elementGuidId>ccf32599-53cc-4573-9af2-36b251fb2c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;DashboardCardstyes__Root-sc-8py5uv-0 ibetEP&quot;]/div[@class=&quot;DashboardCardstyes__Container-sc-8py5uv-2 gsnPml&quot;]/div[@class=&quot;DashboardCardstyes__Wrapper-sc-8py5uv-1 kpPOAp&quot;]/div[@class=&quot;DashboardCardstyes__LinkWrapper-sc-8py5uv-5 gMOGcJ&quot;]/a[@class=&quot;Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE&quot;][count(. | //*[@class = 'Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE' and @href = '/en/account/limits/' and (text() = 'Review' or . = 'Review')]) = count(//*[@class = 'Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE' and @href = '/en/account/limits/' and (text() = 'Review' or . = 'Review')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/account/limits/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Review</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;DashboardCardstyes__Root-sc-8py5uv-0 ibetEP&quot;]/div[@class=&quot;DashboardCardstyes__Container-sc-8py5uv-2 gsnPml&quot;]/div[@class=&quot;DashboardCardstyes__Wrapper-sc-8py5uv-1 kpPOAp&quot;]/div[@class=&quot;DashboardCardstyes__LinkWrapper-sc-8py5uv-5 gMOGcJ&quot;]/a[@class=&quot;Buttonsstyles__BorderLink-sc-19vsptk-3 dFhlSE&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Review')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Always Play Safe'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep Your Account Secure'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Review']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/account/limits/')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Review')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
>>>>>>> branch 'master' of https://github.com/WhiteOrg/SCAutoTests
