<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Withdraw</name>
   <tag></tag>
   <elementGuidId>cd75a8a3-824d-477c-9585-e9d74c10f58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;Welcomestyles__Root-e6pbod-0 vcsgA&quot;]/div[@class=&quot;Welcomestyles__MemberBalanceWrapper-e6pbod-6 egLSyV&quot;]/div[@class=&quot;Welcomestyles__ButtonWrapper-e6pbod-1 fvwzTK&quot;]/div[@class=&quot;Welcomestyles__WithdrawButton-e6pbod-4 hmzGao&quot;]/a[@class=&quot;Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD&quot;][count(. | //a[@class = 'Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD' and @href = '/en/account/withdraw/' and (text() = 'Withdraw' or . = 'Withdraw')]) = count(//a[@class = 'Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD' and @href = '/en/account/withdraw/' and (text() = 'Withdraw' or . = 'Withdraw')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/account/withdraw/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Withdraw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;Welcomestyles__Root-e6pbod-0 vcsgA&quot;]/div[@class=&quot;Welcomestyles__MemberBalanceWrapper-e6pbod-6 egLSyV&quot;]/div[@class=&quot;Welcomestyles__ButtonWrapper-e6pbod-1 fvwzTK&quot;]/div[@class=&quot;Welcomestyles__WithdrawButton-e6pbod-4 hmzGao&quot;]/a[@class=&quot;Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Withdraw')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€71.40'])[3]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Information'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/account/withdraw/')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€192.20'])[3]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£345.00'])[3]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£325.00'])[3]/following::a[2]</value>
   </webElementXpaths>
</WebElementEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Withdraw</name>
   <tag></tag>
   <elementGuidId>cd75a8a3-824d-477c-9585-e9d74c10f58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;Welcomestyles__Root-e6pbod-0 vcsgA&quot;]/div[@class=&quot;Welcomestyles__MemberBalanceWrapper-e6pbod-6 egLSyV&quot;]/div[@class=&quot;Welcomestyles__ButtonWrapper-e6pbod-1 fvwzTK&quot;]/div[@class=&quot;Welcomestyles__WithdrawButton-e6pbod-4 hmzGao&quot;]/a[@class=&quot;Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD&quot;][count(. | //a[@class = 'Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD' and @href = '/en/account/withdraw/' and (text() = 'Withdraw' or . = 'Withdraw')]) = count(//a[@class = 'Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD' and @href = '/en/account/withdraw/' and (text() = 'Withdraw' or . = 'Withdraw')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/account/withdraw/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Withdraw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Masterstyles__Root-sc-5xhbmh-0 hcQHET&quot;]/div[@class=&quot;Masterstyles__Page-sc-5xhbmh-2 dKHfcF&quot;]/div[@class=&quot;Accountstyles__Root-sc-1gqzym-0 jcaarZ&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Accountstyles__Layout-sc-1gqzym-1 gPolvr&quot;]/div[@class=&quot;Accountstyles__Page-sc-1gqzym-3 kFzIbh&quot;]/div[@class=&quot;Accountstyles__PageContent-sc-1gqzym-4 iKsvyc&quot;]/div[@class=&quot;Accountstyles__AccountWrapper-sc-1gqzym-6 BqnTF&quot;]/div[@class=&quot;Welcomestyles__Root-e6pbod-0 vcsgA&quot;]/div[@class=&quot;Welcomestyles__MemberBalanceWrapper-e6pbod-6 egLSyV&quot;]/div[@class=&quot;Welcomestyles__ButtonWrapper-e6pbod-1 fvwzTK&quot;]/div[@class=&quot;Welcomestyles__WithdrawButton-e6pbod-4 hmzGao&quot;]/a[@class=&quot;Buttonsstyles__SolidLink-sc-19vsptk-2 eMNooD&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Withdraw')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€71.40'])[3]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Information'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/account/withdraw/')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€192.20'])[3]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£345.00'])[3]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£325.00'])[3]/following::a[2]</value>
   </webElementXpaths>
</WebElementEntity>
>>>>>>> branch 'master' of https://github.com/WhiteOrg/SCAutoTests
