<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpswwwgamcareorgukget-adviceself-assessment-toolVBwEHvldXww</name>
   <tag></tag>
   <elementGuidId>40f9d7a6-a502-4da2-b0a8-9b767ad417db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div/div/div/div[2]/div/div[3]/p/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Supportstyles__Root-h2f8v7-0 ckxgoN&quot;]/div[@class=&quot;Supportstyles__Page-h2f8v7-2 liMFoM&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Supportstyles__Layout-h2f8v7-4 kVPWgr&quot;]/div[@class=&quot;Supportstyles__Row-h2f8v7-6 iBXcPf&quot;]/div[@class=&quot;Supportstyles__PageContent-h2f8v7-10 ivzFYu&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 jdttix&quot;]/div[3]/p[1]/a[1][count(. | //a[@href = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' and (text() = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' or . = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')]) = count(//a[@href = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' and (text() = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' or . = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Supportstyles__Root-h2f8v7-0 ckxgoN&quot;]/div[@class=&quot;Supportstyles__Page-h2f8v7-2 liMFoM&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Supportstyles__Layout-h2f8v7-4 kVPWgr&quot;]/div[@class=&quot;Supportstyles__Row-h2f8v7-6 iBXcPf&quot;]/div[@class=&quot;Supportstyles__PageContent-h2f8v7-10 ivzFYu&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 jdttix&quot;]/div[3]/p[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div/div/div/div[2]/div/div[3]/p/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I suspect I have a gambling problem, what do I do now?'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat with support'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible Gaming Page'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What limits can I set on my account?'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
   </webElementXpaths>
</WebElementEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpswwwgamcareorgukget-adviceself-assessment-toolVBwEHvldXww</name>
   <tag></tag>
   <elementGuidId>40f9d7a6-a502-4da2-b0a8-9b767ad417db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div/div/div/div[2]/div/div[3]/p/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Supportstyles__Root-h2f8v7-0 ckxgoN&quot;]/div[@class=&quot;Supportstyles__Page-h2f8v7-2 liMFoM&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Supportstyles__Layout-h2f8v7-4 kVPWgr&quot;]/div[@class=&quot;Supportstyles__Row-h2f8v7-6 iBXcPf&quot;]/div[@class=&quot;Supportstyles__PageContent-h2f8v7-10 ivzFYu&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 jdttix&quot;]/div[3]/p[1]/a[1][count(. | //a[@href = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' and (text() = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' or . = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')]) = count(//a[@href = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' and (text() = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww' or . = 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/div[@class=&quot;Supportstyles__Root-h2f8v7-0 ckxgoN&quot;]/div[@class=&quot;Supportstyles__Page-h2f8v7-2 liMFoM&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 Supportstyles__Layout-h2f8v7-4 kVPWgr&quot;]/div[@class=&quot;Supportstyles__Row-h2f8v7-6 iBXcPf&quot;]/div[@class=&quot;Supportstyles__PageContent-h2f8v7-10 ivzFYu&quot;]/div[@class=&quot;basestyles__Container-sc-1odkkkx-0 jdttix&quot;]/div[3]/p[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div/div/div/div[2]/div/div[3]/p/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I suspect I have a gambling problem, what do I do now?'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat with support'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible Gaming Page'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What limits can I set on my account?'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.gamcare.org.uk/get-advice/self-assessment-tool#.VBwEHvldXww')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
   </webElementXpaths>
</WebElementEntity>
>>>>>>> branch 'master' of https://github.com/WhiteOrg/SCAutoTests
